### ISSUE TITLE
Revise Native module version docs about updating RN versions and validating on other platforms

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows-samples#244] opened 2020-09-04 18:45 UTC
Yeah, these values should be dependent on what the min version of RNW you want to support.   So this should be something like:
`yarn add react-native-windows@>=0.62 --peer`

Also, if you are working on an existing community project, you can't just update the RN dev version without making changes to the android/ios test projects assuming they have some.  --  You will likely need to do some kind of RN update work flow, depending on what is in the repo.

_Originally posted by @acoates-ms in https://github.com/microsoft/react-native-windows-samples/pull/243#discussion_r483784695_

**Comment by chrisglein** [comment] 2020-09-10 22:25
Duplicate of #253

**Closed** 2020-09-10 22:27 UTC
Labels: Extensions, Needs: triage :mag:
