### ISSUE TITLE
Need better instructions on adding Windows support for native modules

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows-samples#229] opened 2020-08-30 23:08 UTC
microsoft/react-native-windows#4993 renamed the package `react-native-windows-override-tools` to `react-native-platform-override`. However RNW 0.62 still uses the old name which is not available on npmjs/yarnpkg

Repro:
- clone a native module repo to add support for windows (e.g. clipboard)
- follow the instructions and run `yarn add react-native-windows@0.62 --peer`
- `cd node_modules\react-native-windows` and run `yarn`, you get a error about missing package:
`error An unexpected error occurred: "https://registry.yarnpkg.com/react-native-windows-override-tools: Not found".`

If I replace the entry in RNW's `package.json` with `react-native-platform-override` then I get prompted for what version to use. If I choose 0.0.1 then `yarn build` later fails when trying to build react-native-windows-codegen because the published package doesn't include a built-to-javascript cli.js so I have to manually go into `clipboard\node_modules\react-native-windows\node_modules\react-native-windows-codegen\` and run `yarn build` there manually

**Comment by chrisglein** [comment] 2020-08-31 18:20
Steps here should be made to be correct: https://microsoft.github.io/react-native-windows/docs/native-modules-setup#adding-windows-support-to-an-existing-library

It's suspected that these steps may be creating issues for modules migrating from 0.62 to 0.63. The instructions set you up to work for exactly 0.62.0, not 0.62 and greater.

Side note, that isn't the most discoverable document. I'd argue it should be a top-level document, not a part of another one.

**Comment by chrisglein** [comment] 2020-09-10 22:26
Duplicate of #253

**Closed** 2020-09-10 22:27 UTC
Labels: Extensions, bug, documentation
