### ISSUE TITLE
It would be better if documentation have a showcase page.

### ISSUE THREAD

**Issue by TheEhsanSarshar** [microsoft/react-native-windows-samples#278] opened 2020-07-26 07:02 UTC
if it have a showcase page that shows some apps that built with react-native-windows

**Comment by EhsanSarshar** [comment] 2020-10-07 06:20
@kikisaints ???

**Comment by chrisglein** [comment] 2021-09-21 01:12
Duplicate of #517

**Closed** 2021-09-22 03:00 UTC
Labels: duplicate, enhancement
