### ISSUE TITLE
Homepage Responsive Design

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows-samples#448] opened 2021-05-25 12:47 UTC
The CSS we are using specifically for the main page does not generate a usable page on mobile.

![0B83CECB-C51C-4EA1-BC36-2448073296A8](https://user-images.githubusercontent.com/835219/119500414-a0d54f00-bd1c-11eb-99fc-810444763025.png)
![0F017CDA-13B7-4127-99CD-2DCA354C2C4E](https://user-images.githubusercontent.com/835219/119500422-a337a900-bd1c-11eb-9b59-142ac134f3e7.png)

**Comment by asklar** [comment] 2021-05-25 17:22
Duplicate of #147 (or related at least)

**Closed** 2021-05-27 18:43 UTC
Labels: duplicate
