### ISSUE TITLE
Add sample that shows wrapping of a complex WinUI control from RNW

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows-samples#299] opened 2020-10-14 22:28 UTC
We need a sample that shows best practices for wrapping a somewhat complex WinUI control in JS and using the same in an RNW app, exercising the ViewManager code and making the guidance for the same better.

**Comment by chrisglein** [comment] 2020-10-15 18:19
Grouped list view would be a good choice to show a large black-box control (no RN hosted content within the list).

**Comment by harinikmsft** [comment] 2020-12-01 00:25
I won't be able to get to this now, moving to backlog until we have the next milestone up.

**Comment by chrisglein** [comment] 2021-04-24 01:37
Duplicate of #301

**Closed by chrisglein** 2021-04-24 01:38 UTC
Labels: enhancement, samples
