### ISSUE TITLE
Revise "Using Windows Brushes and Responding to Themes" Page

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows-samples#204] opened 2020-08-24 09:54 UTC
We have a banner mentioning AppTheme is deprecated, but still have a page instructing to use that and windowbrush. Need to update to add caveats around Appearance, PlatformColor, while AppTheme is still around.

**Comment by harinikmsft** [comment] 2020-08-25 16:16
Duplicate of #167

**Closed by harinikmsft** 2020-08-25 16:16 UTC
Labels: Needs: triage :mag:
