### ISSUE TITLE
Certificate not found error when executing the rss reader sample

### ISSUE THREAD

**Issue by sibille** [microsoft/react-native-windows-samples#139] opened 2020-06-10 11:25 UTC
Following the instructions from https://github.com/microsoft/react-native-windows-samples/tree/master/samples/rssreader#run-the-sample-on-windows-10 I get the following error when running` npx react-native run-windows --logging`. 

![image](https://user-images.githubusercontent.com/24698018/84262083-3fbd6700-ab1d-11ea-9434-4867695f0e5a.png)

Replacing the certificate with a test-certificate makes the sample work.

**Comment by chrisglein** [comment] 2020-06-11 18:43
Potentially related to this: https://github.com/microsoft/react-native-windows/issues/3592

Sample app needs a certificate that isn't specific to the person that authored it.
The RssReader is probably different here because it was actually published to the store.

@qmatteoq Do you know how we should be setting up the certificate for this sample?

**Comment by qmatteoq** [comment] 2020-06-12 12:16
@sibille can you check if, inside the windows/rssreader folder, do you have a file called rssreader.pfx?

It's strange because I have double checked and the:

1) The rssreader.pfx file is checked inside the repository
2) The thumbprint of the certificate displayed in the error matches the thumbprint of the rssreader.pfx one.

Thanks!

**Comment by sibille** [comment] 2020-06-12 12:26
There is a rssreader.pfx, but can't say if the error matches the thumbprint, it's password protected.

**Comment by qmatteoq** [comment] 2020-06-12 12:32
If you open the Visual Studio solution, double click on the Package.appxmanifest file and move to the Packaging section, you should see something like this:

![image](https://user-images.githubusercontent.com/1230332/84502853-62848280-acb9-11ea-8b90-1957aad0189f.png)

And you click on Choose Certificate, you should see the Thumbprint: 

![image](https://user-images.githubusercontent.com/1230332/84502891-77611600-acb9-11ea-8146-85d3783bb8b4.png)

Unfortunately I'm not able to reproduce the problem from my side. I just tried to clone the repo in a new folder to start from scratch, but the application started fine when I launched `npx react-native run-windows`.

**Comment by sibille** [comment] 2020-06-12 12:42
I think it's related to the pfx being password protected and not installed on my machine.

![image](https://user-images.githubusercontent.com/24698018/84503329-4a613300-acba-11ea-873e-5dea11c353ec.png)

**Comment by qmatteoq** [comment] 2020-06-12 12:44
Can you try to run `npx react-native run-windows` again but, this time, from an elevated terminal?

The certificate is indeed password protected, but the password (together with the thumbprint) are stored in the .vcxproj file:

```
<PackageCertificateThumbprint>84F22247968D3819755876B7A9DB232FC5DE51E2</PackageCertificateThumbprint>
<PackageCertificatePassword>password</PackageCertificatePassword>
```

The `npx react-native run-windows` command should take care of installing the certificate as part of the deployment process (this is why you need an admin prompt the first time you launch the script).

**Comment by sibille** [comment] 2020-06-12 13:17
I think I tried the first time on an elevated terminal too, but just tried again with the same error. After installing the certificate on my machine it works fine.

**Comment by qmatteoq** [comment] 2020-06-12 13:20
Thanks for the feedback. It seems this is indeed related with the bug that @chrisglein highlighted. There are some issues going on with the PowerShell command which takes care of deploying the app and install the certificate.

**Comment by chiaramooney** [comment] 2021-09-21 16:53
Another option in the meantime would be to use `npx react-native run-windows --msbuildprops AppxPackageSigningEnabled=False` for debug builds and `npx react-native run-windows --release --deploy-from-layout --msbuildprops AppxPackageSigningEnabled=False`

**Comment by chiaramooney** [comment] 2021-12-28 18:11
Certificates were removed from Rssreader sample in #600. Issue should no longer apply. Closing issue now.

**Closed by chiaramooney** 2021-12-28 18:11 UTC
Labels: bug, samples
