### ISSUE TITLE
Create/link app guide for RNW version update best practices

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows-samples#258] opened 2020-09-14 18:59 UTC
We hit [this issue](https://github.com/microsoft/react-native-windows/issues/5965) in triage. I wanted to point them to our upgrade guide, but... either I couldn't find it (link needs to be surfaced more obviously) or it doesn't exist. Our recommendation is basically that you create a new blank project and copy over your app content; that way gets you the cleanest app template. I swear I've seen that written done somewhere, but I couldn't find it. 

We may not need to necessarily create new content here, just link to it. For core RN upgrade issues [support is available here](https://github.com/react-native-community/upgrade-support).

**Comment by chiaramooney** [comment] 2021-12-03 00:32
Dupe of #533

**Closed by chiaramooney** 2021-12-03 00:32 UTC
Labels: documentation, enhancement, Engineering Improvement Candidate
