### ISSUE TITLE
How to add macOS support to existing native module?

### ISSUE THREAD

**Issue by mrousavy** [microsoft/react-native-windows-samples#265] opened 2020-09-04 12:26 UTC
Hi!

I couldn't find any documentation on how to add macOS support to an existing native module, so I'm sorry for asking this here.

I'm trying to add macOS support for my library [react-native-blurhash](https://github.com/mrousavy/react-native-blurhash/tree/support-macos), but I can't seem to figure out how to create the `.xcodeproj` file.

It always complains that the native module cannot be found:

![Screenshot 2020-09-04 at 14 23 41](https://user-images.githubusercontent.com/15199031/92238797-3cd2d800-eeba-11ea-84a4-cba26b567a8b.png)

TL;DR: I have no idea how to create my `macos/Blurhash.xcodeproj` to add the native module to my example app. My current source code is [on this branch](https://github.com/mrousavy/react-native-blurhash/tree/support-macos), and contains a wacky `macos/Blurhash.xcodeproj` which doesn't link correctly (as you can see).

Also, here's my output of `pod install` in the `example/macos` folder:

```
macos 🔥 pod install
Auto-linking React Native module for target `example-iOS`: react-native-blurhash
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native-macos/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `RCT-Folly` from `../node_modules/react-native-macos/third-party-podspecs/RCT-Folly.podspec`
Fetching podspec for `boost-for-react-native` from `../node_modules/react-native-macos/third-party-podspecs/boost-for-react-native.podspec`
Fetching podspec for `glog` from `../node_modules/react-native-macos/third-party-podspecs/glog.podspec`
Downloading dependencies
Installing CocoaAsyncSocket (7.6.4)
Installing CocoaLibEvent (1.0.0)
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.62.2)
Installing FBReactNativeSpec (0.62.2)
Installing Flipper (0.33.1)
Installing Flipper-DoubleConversion (1.1.7)
Installing Flipper-Folly (2.2.0)
Installing Flipper-Glog (0.3.6)
Installing Flipper-PeerTalk (0.0.4)
Installing Flipper-RSocket (1.1.0)
Installing FlipperKit (0.33.1)
Installing OpenSSL-Universal (1.0.2.19)
Installing RCT-Folly (2018.10.22.00)
Installing RCTRequired (0.62.2)
Installing RCTTypeSafety (0.62.2)
Installing React (0.62.2)
Installing React-Core (0.62.2)
Installing React-CoreModules (0.62.2)
Installing React-RCTActionSheet (0.62.2)
Installing React-RCTAnimation (0.62.2)
Installing React-RCTBlob (0.62.2)
Installing React-RCTImage (0.62.2)
Installing React-RCTLinking (0.62.2)
Installing React-RCTNetwork (0.62.2)
Installing React-RCTSettings (0.62.2)
Installing React-RCTText (0.62.2)
Installing React-RCTVibration (0.62.2)
Installing React-cxxreact (0.62.2)
Installing React-jsi (0.62.2)
Installing React-jsiexecutor (0.62.2)
Installing React-jsinspector (0.62.2)
Installing ReactCommon (0.62.2)
Installing Yoga (1.14.0)
Installing YogaKit (1.18.1)
Installing boost-for-react-native (1.63.0)
Installing glog (0.3.5)
Installing react-native-blurhash (1.0.23)
Generating Pods project
Integrating client project
Pod installation complete! There are 49 dependencies from the Podfile and 38 total pods installed.
```

> At the top it says `Auto-linking React Native module for target 'example-iOS': react-native-blurhash`, I suppose that's the problem here?

**Comment by chrisglein** [comment] 2020-09-16 17:41
Duplicate of #159.
This is definitely some documentation we want to flesh out. Thanks for your questions and this detail will be linked to that issue.

**Closed by chrisglein** 2020-09-16 17:41 UTC
Labels: Needs: triage :mag:
